title: Learning Git and GitHub
author: conFuchsian
email: fuschia_sage@protonmail.com
theme: minima
description: A header with a body of text describing my experience with GitHub

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: conFuchsian # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
